import Link from 'next/link'
import './globals.css' //common.css

export const metadata = {
  title: 'Next 기초',
  description: 'Generated by create next app',
}

//↓ 컴포넌트
export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body>
        <header className='txt'>
          <Link href='/'>HOME</Link>
          <Link href='/test'>TEST</Link>
          <Link href='/js'>js</Link>
        </header>

        <main>
          {children}
          {/* 지정해주지 않아도 page.js가 children에 들어감 */}
        </main>

        <footer>@test.com</footer>
      </body>
    </html>
  )
}
